# Configuration Jekyll de base

title: "Mon Projet d'Objets Connectés"
description: "Exploration des Objets Connectés avec Arduino et Fusion 360."

# Configuration du thème
theme: jekyll-theme-minimal

# Configuration des couleurs
colors:
  background: "#f8f8f8"  # Couleur de fond
  text: "#333333"        # Couleur du texte
  link: "#007bff"        # Couleur des liens

# Configuration de la police
font:
  family: "Arial, sans-serif"
  size: 16px

# D'autres configurations peuvent être ajoutées en fonction de vos besoins
